<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('apartments')->truncate();
        DB::table('apartments')->insert([
            [
                'id' => 1,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 2,
                'apartmentName' => 'A02',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 3,
                'apartmentName' => 'A03',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 4,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 5,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 6,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 7,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 8,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 9,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 10,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 11,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 12,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 13,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 14,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 15,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 16,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 17,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 18,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 19,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ], [
                'id' => 20,
                'apartmentName' => 'A01',
                'address' => 'Hà Nội',
                'price' => 3000000,
                'generalInformation' => 'nhà đẹp',
                'privateInformation' => 'giá rẻ',
                'avatar' => 'https://giathuecanho.com/wp-content/uploads/2019/03/kingdom-101.jpg.webp',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
        ]);
    }
}
